Controllers/BloodWorkController.cs
using MedChartBloodWork.Data;
using MedChartBloodWork.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MedChartBloodWork.Controllers
{
    public class BloodWorkController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly ApplicationDbContext _context;
        private readonly ILogger<BloodWorkController> _logger;

        public BloodWorkController(ILogger<BloodWorkController> logger, UserManager<ApplicationUser> userManager, ApplicationDbContext context)
        {
            _logger = logger;
            _userManager = userManager;
            _context = context;

        }
        //This shows list of all blood work of that specific patient using ID

        public async Task<IActionResult> Index()
        {
            //this will assign entire data of ASPNETUSERS Table value to user. This is how we capture ID of patient using this application if they are signed in
            var user = await _userManager.GetUserAsync(HttpContext.User);

            //This will filter the list of bloodwork only of the specific patient who has signed in and stores them in List and sends to vIEW PAGE
            List<BloodWork> ListOfBloodWork = _context.BloodWork.Where(x => x.ApplicationUserID == user.Id).ToList();
            return View(ListOfBloodWork);
        }

        //Adding new blood work . Below code will throw to add new bloodwork viewpage
        [HttpGet]
        public IActionResult AddBloodWork()
        {
            //this will assign entire data of ASPNETUSERS Table value to user. This is how we capture ID of patient using this application if they are signed in
            //var user = await _userManager.GetUserAsync(HttpContext.User);
            //var BloodWorkAddPatient = _context.BloodWork.Where(x => x.ApplicationUserID == user.Id).FirstOrDefault();
            return View();
        }

        //Below actionmethod has parameter which has data from add new blood work form that will be added to tables
        [HttpPost]
        public async Task<IActionResult> AddBloodWork(BloodWork bloodwork)
        {
            //this will assign entire data of ASPNETUSERS Table value to user. This is how we capture ID of patient using this application if they are signed in
            var user = await _userManager.GetUserAsync(HttpContext.User);
            //Instantiating method to assign data that came from form to ta database table
            BloodWork bWork = new BloodWork();
            bWork.DateCreated = bloodwork.DateCreated;
            bWork.ExamDate = bloodwork.ExamDate;
            bWork.ResultDate = bloodwork.ResultDate;
            bWork.Description = bloodwork.Description;
            bWork.Hemoglobin = bloodwork.Hemoglobin;
            bWork.Hematocrit = bloodwork.Hematocrit;
            bWork.WhiteBloodCellCount = bloodwork.WhiteBloodCellCount;
            bWork.RedBloodCellCount = bloodwork.RedBloodCellCount;
            bWork.ApplicationUserID = (user.Id);
            //Adds record in new row and saves changes
            _context.BloodWork.Add(bWork);
            _context.SaveChanges();
            //The code below will send to Index page which has list of patient's blood work
            return RedirectToAction(nameof(Index));
        }
       
        //This shows the Edit View
        public async Task<IActionResult> Edit(int? id)
        {
            //checking null value if any
            if (id == null)
            {
                return NotFound();
            }
            //this will assign entire data of ASPNETUSERS Table value to user. This is how we capture ID of patient using this application if they are signed in
            var user = await _userManager.GetUserAsync(HttpContext.User);

            //This will filter the list of bloodwork only of the specific patient who has signed in and stores them in List and sends to vIEW PAGE
            var ToBeEditedPatient = _context.BloodWork.Where(x => x.BloodWorkID == id).FirstOrDefault();
            return View(ToBeEditedPatient);
        }

  
        //This is bringing new data in the parameter which is updated in form 
        public async Task<IActionResult> EditPost(BloodWork bloodWork)
        
        {
            //this will assign entire data of ASPNETUSERS Table value to user. This is how we capture ID of patient using this application if they are signed in
            var user = await _userManager.GetUserAsync(HttpContext.User);
            //Instantiating method to assign data that came from form to ta database table
            if (ModelState.IsValid)
            {
                var bWork = _context.BloodWork.Where(x => x.BloodWorkID == bloodWork.BloodWorkID).FirstOrDefault();
                bWork.DateCreated = bloodWork.DateCreated;
                bWork.ExamDate = bloodWork.ExamDate;
                bWork.ResultDate = bloodWork.ResultDate;
                bWork.Description = bloodWork.Description;
                bWork.Hemoglobin = bloodWork.Hemoglobin;
                bWork.Hematocrit = bloodWork.Hematocrit;
                bWork.WhiteBloodCellCount = bloodWork.WhiteBloodCellCount;
                bWork.RedBloodCellCount = bloodWork.RedBloodCellCount;
                bWork.ApplicationUserID = Convert.ToString(user.Id);
                _context.Update(bWork);
                _context.SaveChanges();
            }

            //Updates record in existing row and saves changes

            //The code below will send to Index page which has list of patient's blood work
            return RedirectToAction("Index");
        }

        [HttpGet]
        //This shows the Details View
        public async Task<IActionResult> Details(int? id)
        {
            //this will assign entire data of ASPNETUSERS Table value to user. This is how we capture ID of patient using this application if they are signed in
            var user = await _userManager.GetUserAsync(HttpContext.User);

            //This will filter the list of bloodwork only of the specific patient who has signed in and stores them in List and sends to vIEW PAGE
            var DetailsOfAPatient = _context.BloodWork.Where(x => x.BloodWorkID == id).FirstOrDefault();
            return View(DetailsOfAPatient);
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int? id)
        {
            //this will assign entire data of ASPNETUSERS Table value to user. This is how we capture ID of patient using this application if they are signed in
            var user = await _userManager.GetUserAsync(HttpContext.User);
            var BloodWorkAddPatient = _context.BloodWork.Where(x => x.BloodWorkID == id).FirstOrDefault();
            //passing the specific id in the view so that delete view can be seen by user during delete event
            return View(BloodWorkAddPatient);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(BloodWork bloodWork)
        {
            //this will assign entire data of ASPNETUSERS Table value to user. This is how we capture ID of patient using this application if they are signed in
            var user = await _userManager.GetUserAsync(HttpContext.User);
            var BloodWorkAddPatient = _context.BloodWork.Where(x => x.BloodWorkID == bloodWork.BloodWorkID).FirstOrDefault();
            _context.BloodWork.Remove(BloodWorkAddPatient);
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }
    }
}

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MedChartBloodWork</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img style="height:65px; width:250px" src="~/images/logo.png"/></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="btn btn-success" asp-area="" asp-controller="BloodWork" asp-action="Index">List of all Blood Works</a>
                        </li>
                        @*<li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>*@
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - MedChartBloodWork - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>